# Generated by Django 4.1.6 on 2023-02-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('colour', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1234)),
                ('details', models.CharField(max_length=1234)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='punchout_rest.category')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='punchout_rest.tag')),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punchout_rest.task')),
            ],
        ),
    ]
