# Generated by Django 4.1.6 on 2023-04-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punchout_rest', '0002_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='boardId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='punchout_rest.board'),
            preserve_default=False,
        ),
    ]
