# Generated by Django 4.1.6 on 2023-04-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchout_rest', '0003_category_boardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='colour',
            field=models.CharField(max_length=7),
        ),
    ]
