# Generated by Django 4.1.6 on 2023-04-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchout_rest', '0004_alter_category_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='colour',
            field=models.CharField(max_length=9),
        ),
    ]
